sudo: true
language: node_js
node_js:
  - 0.12
  - 4
  - 5
  - 6
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6
script: npm test
before_install:
  - git clone -q https://github.com/ramunasd/osmctools.git
  - cd osmctools
  - autoreconf --install
  - ./configure
  - sudo make dist-all
  - cd ..
cache:
  directories:
    - node_modules
before_script:
  - npm prune
