sudo: true
language: node_js
node_js:
  - 0.12
  - 4
  - 5
  - 6
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6
script: npm test
before_install:
  - wget -O - http://m.m.i24.cc/osmfilter.c |cc -x c - -O3 -o /usr/local/bin/osmfilter
  - wget -O - http://m.m.i24.cc/osmconvert.c | cc -x c - -lz -O3 -o /usr/local/bin/osmconvert
cache:
  directories:
    - node_modules
before_script:
  - npm prune
