sudo: true
language: node_js
node_js:
  - 0.10
  - 0.12
  - 4.4
  - 5.8
matrix:
    allow_failures:
        - node_js: 4.4
        - node_js: 5.8
before_install:
  - wget --quiet http://security.ubuntu.com/ubuntu/pool/universe/o/osmctools/osmctools_0.3-1_amd64.deb
  - sudo dpkg -i osmctools_0.3-1_amd64.deb
