sudo: true
language: node_js
node_js:
  - 0.1
  - 0.12
  - 4.4
  - 5.8
matrix:
  allow_failures:
    - node_js: 4.4
    - node_js: 5.8
script: npm test
before_install:
  - npm i -g npm@^3.0.0
  - cd osmctools
  - autoreconf --install
  - ./configure
  - sudo make dist-all
  - cd ..
