sudo: true
language: node_js
node_js:
  - 0.10
  - 0.12
  - 4.4
  - 5.8
matrix:
    allow_failures:
        - node_js: 4.4
        - node_js: 5.8
before_install:
  - git clone -q https://github.com/ramunasd/osmctools.git
  - cd osmctools
  - autoreconf --install
  - ./configure
  - sudo make dist-all
